name: Build DEV Jars
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
  push:
    branches:
      - master
    paths-ignore:
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Get commit hash
        id: hash
        run: echo "sha_short=$(git rev-parse --short ${{github.sha}})" >> $GITHUB_OUTPUT
      - name: Get version
        id: version
        run: echo "version=$(grep version gradle.properties | cut -d"=" -f2 | xargs)" >> $GITHUB_OUTPUT
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: |
          chmod 777 gradlew
          ./gradlew shadowJar
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "git_hash=$git_hash" >> $GITHUB_ENV
          echo "snapshotVersion=5.5-SNAPSHOT" >> $GITHUB_ENV
          echo "artifactPath=$(pwd)/builds" >> $GITHUB_ENV
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SoraxPhysic-${{ env.git_hash }}-${{ steps.version.outputs.version }}.jar
          path: build/libs/SoraxPhysic*.jar
