name: Build DEV Jars
on:
  pull_request:
    paths-ignore:
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
  push:
    paths-ignore:
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
jobs:
  build_dev_jars:
    name: Build DEV jars
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Gradle
        run: |
          chmod 777 gradlew
          ./gradlew shadowJar
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "git_hash=$git_hash" >> $GITHUB_ENV
          echo "snapshotVersion=5.5-SNAPSHOT" >> $GITHUB_ENV
          echo "artifactPath=$(pwd)/builds" >> $GITHUB_ENV
      - name: Upload Plugin jar
        uses: actions/upload-artifact@v3
        with:
          name: SoraxPhysic-${{ env.git_hash }}.jar
          path: ${{ env.artifactPath }}/SoraxPhysic-1.0-SNAPSHOT-all.jar
